"""
This type stub file was generated by pyright.
"""

import logging
from pathlib import Path
from abc import ABC, abstractmethod

"""
Centralized logging configuration for the ML Markdown project.

This module provides a standardized way to configure and use Python's 
logging module across the entire project. It ensures consistent log 
formatting, appropriate log levels, and centralized configuration.

Usage:
    from library.lm_logging import get_logger, ConsoleLogger, 
        FileLogger, ExceptionConsoleLogger

    # Use the abstract interface implementations
    console_logger = ConsoleLogger(__name__)
    file_logger = FileLogger(__name__, "app.log")
    exception_logger = ExceptionConsoleLogger(__name__)

    # Or use the traditional logger
    logger = get_logger(__name__)
"""
class ILogger(ABC):
    """
    Abstract interface for logging functionality.
    """
    @abstractmethod
    def set_level(self, level: int) -> None:
        """Set the logging level for the logger."""
        ...
    
    @abstractmethod
    def info(self, msg: str) -> None:
        """Log an informational message."""
        ...
    
    @abstractmethod
    def error(self, msg: str) -> None:
        """Log an error message."""
        ...
    
    @abstractmethod
    def warning(self, msg: str) -> None:
        """Log a warning message."""
        ...
    
    @abstractmethod
    def critical(self, msg: str) -> None:
        """Log a critical message."""
        ...
    


class ConsoleLogger(ILogger):
    """
    A console logger implementation that uses logging.Logger as a 
    delegate. Logs messages to the console using Python's built-in 
    logging module.
    """
    def __init__(self, name: str = ...) -> None:
        """
        Initialize the ConsoleLogger with a specific logger name.

        Args:
            name: The name of the logger, typically __name__ to use 
            the module name
        """
        ...
    
    def set_level(self, level: int) -> None:
        """Set the logging level for the logger."""
        ...
    
    def info(self, msg: str) -> None:
        """Log an informational message."""
        ...
    
    def error(self, msg: str) -> None:
        """Log an error message."""
        ...
    
    def warning(self, msg: str) -> None:
        """Log a warning message."""
        ...
    
    def critical(self, msg: str) -> None:
        """Log a critical message."""
        ...
    


class FileLogger(ILogger):
    """
    A file logger implementation that uses logging.Logger as a 
    delegate. Logs messages to a specified file using Python's 
    built-in logging module.
    """
    def __init__(self, name: str = ..., log_file: str | Path = ...) -> None:
        """
        Initialize the FileLogger with a specific logger name and 
        file path.

        Args:
            name: The name of the logger, typically __name__ to use 
                the module name
            log_file: Path to the log file where messages will be 
                written
        """
        ...
    
    def set_level(self, level: int) -> None:
        """Set the logging level for the logger."""
        ...
    
    def info(self, msg: str) -> None:
        """Log an informational message."""
        ...
    
    def error(self, msg: str) -> None:
        """Log an error message."""
        ...
    
    def warning(self, msg: str) -> None:
        """Log a warning message."""
        ...
    
    def critical(self, msg: str) -> None:
        """Log a critical message."""
        ...
    


class FileConsoleLogger(ILogger):
    """
    A file logger implementation that uses logging.Logger as a 
    delegate. Logs messages to a specified file using Python's 
    built-in logging module, and relays the messages to the console 
    as well.
    """
    console_logger: ILogger
    def __init__(self, name: str = ..., log_file: str | Path = ...) -> None:
        """
        Initialize the FileLogger with a specific logger name and 
        file path.

        Args:
            name: The name of the logger, typically __name__ to use 
                the module name
            log_file: Path to the log file where messages will be 
                written
        """
        ...
    
    def set_level(self, level: int) -> None:
        """Set the logging level for the logger."""
        ...
    
    def info(self, msg: str) -> None:
        """Log an informational message."""
        ...
    
    def error(self, msg: str) -> None:
        """Log an error message."""
        ...
    
    def warning(self, msg: str) -> None:
        """Log a warning message."""
        ...
    
    def critical(self, msg: str) -> None:
        """Log a critical message."""
        ...
    


class ExceptionConsoleLogger(ILogger):
    """
    A console logger implementation that raises exceptions on error 
    and critical calls.

    This logger behaves like ConsoleLogger for info, warning, and 
    set_level methods, but raises exceptions when error() or 
    critical() methods are called.
    The message is still logged before the exception is raised.
    """
    def __init__(self, name: str = ...) -> None:
        """
        Initialize the ExceptionConsoleLogger with a specific logger 
        name.

        Args:
            name: The name of the logger, typically __name__ to use 
                the module name
        """
        ...
    
    def set_level(self, level: int) -> None:
        """Set the logging level for the logger."""
        ...
    
    def info(self, msg: str) -> None:
        """Log an informational message."""
        ...
    
    def error(self, msg: str) -> None:
        """Log an error message and raise an exception."""
        ...
    
    def warning(self, msg: str) -> None:
        """Log a warning message."""
        ...
    
    def critical(self, msg: str) -> None:
        """Log a critical message and raise an exception."""
        ...
    


def get_logger(name: str) -> ILogger:
    """
    Get a logger with the specified name.

    Args:
        name: The name of the logger, typically __name__ to use the 
            module name

    Returns:
        A configured logger instance
    """
    ...

LOG_FORMAT = ...
DATE_FORMAT = ...
def get_logging_logger(name: str) -> logging.Logger:
    """
    Get a logger with the specified name.

    Args:
        name: The name of the logger, typically __name__ to use the 
            module name

    Returns:
        A configured logger instance
    """
    ...

def set_log_level(level: int) -> None:
    """
    Set the log level for all loggers.

    Args:
        level: The logging level (e.g., logging.DEBUG, logging.INFO)
    """
    ...

def add_file_handler(log_file: str | Path) -> None:
    """
    Add a file handler to the root logger to write logs to a file.

    Args:
        log_file: Path to the log file
    """
    ...

