"""
This type stub file was generated by pyright.
"""

from typing import Any, Mapping, TypeGuard

"""
Interface to the pyyaml package.

Layer of functions to work with the output of safe_load to handle
list of dictionaries and cover edge cases. YAML can contain a lot of
content kinds that are not compatible for use with a vector database,
and are not relevant in their use to interact with a language model.
The aim here is to isolate an object that is represented in python as
a dictionary with string keys. This dictionary will be used to
exchange messages with the language model.

Conformant YAML objects consist of dictionaries, or list of
dictionaries of type dict[str, elementary_type] where elementary type
is one of int, float, bool, str.

This module defines types MetadataDict and MetadataValue, which are
union types defining the set of dictionaries and dictionary values
that deemed conformant with the use of LM markdown.

The YAML object contained in a metadata block is decomposed into two,
'part', and 'whole'. The 'part' component is the one that may be used
in the rest of the application, containing a conformant dictionary.
The whole part is kept aside and recomposed with the part when the
whole YAML object is reconstituted.

YAML objects consisting of literals only will raise an exception,
since it is conceivable that the user intended something different.
Byte/imaginary literals are put in whole.
"""
MetadataPrimitive = str | int | bool | float
MetadataValue = (None | MetadataPrimitive | list[MetadataPrimitive] | dict[str, MetadataPrimitive | list[MetadataPrimitive]])
MetadataDict = dict[str, MetadataValue]
ParsedYaml = tuple[dict[str, MetadataValue], list[object]]
def is_metadata_primitive(value: object) -> TypeGuard[MetadataPrimitive]:
    ...

def is_metadata_dict(data: object) -> TypeGuard[MetadataDict]:
    ...

def split_yaml_parse(yamldata: object | None, mapped_keys: Mapping[str, str] | None = ...) -> ParsedYaml:
    """
    Constrain output of parsed yaml objects to a tuple that
    represents a conformant ParsedYaml type, and the original
    object

    Args:
        yamldata: the output of yaml.safe_load()
        mapped_keys: a dict-type to replace keys in the parsed
            yaml object

    Returns:
        a tuple. In the first member of the tuple a conformant
        dictionary with strings as keys and values of conformant
        types. The second member of the tuple is a list of yaml
        data that could not be parsed.
    """
    ...

def desplit_yaml_parse(split_parse: (tuple[Mapping[str, MetadataValue], list[object]] | None)) -> Any:
    """
    Reconstitute the original yaml object from the tuple
    constructed by yaml_parse. Dictionaries that were split
    as some values were not elementary remain split.
    """
    ...

def serialize_yaml_parse(split_parse: (tuple[Mapping[str, MetadataValue], list[object]] | None)) -> str:
    """
    Reconstitute a yaml string from the tuple
    constructed by yaml_parse. Dictionaries that were split
    as some values were not elementary remain split.
    """
    ...

def dump_yaml(x: Any) -> str:
    ...

